/*
 * Created on 4 May 2016 ( Time 15:52:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.business.service;

import java.util.List;

import com.cas.bean.AppUser;

/**
 * Business Service Interface for entity AppUser.
 */
public interface AppUserService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	AppUser findById( Long id  ) ;
	
	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<AppUser> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	AppUser save(AppUser entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	AppUser update(AppUser entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	AppUser create(AppUser entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
