/*
 * Created on 4 May 2016 ( Time 15:52:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.business.service;

import java.util.List;

import com.cas.bean.UserProfile;

/**
 * Business Service Interface for entity UserProfile.
 */
public interface UserProfileService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	UserProfile findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<UserProfile> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UserProfile save(UserProfile entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserProfile update(UserProfile entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserProfile create(UserProfile entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
