/*
 * Created on 4 May 2016 ( Time 15:52:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class AppUser implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 30 )
    private String ssoId;

    @NotNull
    @Size( min = 1, max = 100 )
    private String password;

    @NotNull
    @Size( min = 1, max = 30 )
    private String firstName;

    @NotNull
    @Size( min = 1, max = 30 )
    private String lastName;

    @NotNull
    @Size( min = 1, max = 30 )
    private String email;

    @NotNull
    @Size( min = 1, max = 30 )
    private String state;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setSsoId( String ssoId ) {
        this.ssoId = ssoId;
    }
    public String getSsoId() {
        return this.ssoId;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    public void setFirstName( String firstName ) {
        this.firstName = firstName;
    }
    public String getFirstName() {
        return this.firstName;
    }

    public void setLastName( String lastName ) {
        this.lastName = lastName;
    }
    public String getLastName() {
        return this.lastName;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setState( String state ) {
        this.state = state;
    }
    public String getState() {
        return this.state;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(ssoId);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(state);
        return sb.toString(); 
    } 


}
