/*
 * Created on 4 May 2016 ( Time 15:51:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.cas.bean.AppUserUserProfile;
import com.cas.bean.jpa.AppUserUserProfileEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AppUserUserProfileServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AppUserUserProfileServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AppUserUserProfileEntity' to 'AppUserUserProfile'
	 * @param appUserUserProfileEntity
	 */
	public AppUserUserProfile mapAppUserUserProfileEntityToAppUserUserProfile(AppUserUserProfileEntity appUserUserProfileEntity) {
		if(appUserUserProfileEntity == null) {
			return null;
		}

		//--- Generic mapping 
		AppUserUserProfile appUserUserProfile = map(appUserUserProfileEntity, AppUserUserProfile.class);

		return appUserUserProfile;
	}
	
	/**
	 * Mapping from 'AppUserUserProfile' to 'AppUserUserProfileEntity'
	 * @param appUserUserProfile
	 * @param appUserUserProfileEntity
	 */
	public void mapAppUserUserProfileToAppUserUserProfileEntity(AppUserUserProfile appUserUserProfile, AppUserUserProfileEntity appUserUserProfileEntity) {
		if(appUserUserProfile == null) {
			return;
		}

		//--- Generic mapping 
		map(appUserUserProfile, appUserUserProfileEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}