/*
 * Created on 4 May 2016 ( Time 15:51:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.cas.bean.AppUser;
import com.cas.bean.jpa.AppUserEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AppUserServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AppUserServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AppUserEntity' to 'AppUser'
	 * @param appUserEntity
	 */
	public AppUser mapAppUserEntityToAppUser(AppUserEntity appUserEntity) {
		if(appUserEntity == null) {
			return null;
		}

		//--- Generic mapping 
		AppUser appUser = map(appUserEntity, AppUser.class);

		return appUser;
	}
	
	/**
	 * Mapping from 'AppUser' to 'AppUserEntity'
	 * @param appUser
	 * @param appUserEntity
	 */
	public void mapAppUserToAppUserEntity(AppUser appUser, AppUserEntity appUserEntity) {
		if(appUser == null) {
			return;
		}

		//--- Generic mapping 
		map(appUser, appUserEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}