/*
 * Created on 4 May 2016 ( Time 15:51:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.cas.bean.UserProfile;
import com.cas.bean.jpa.UserProfileEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UserProfileServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UserProfileServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'UserProfileEntity' to 'UserProfile'
	 * @param userProfileEntity
	 */
	public UserProfile mapUserProfileEntityToUserProfile(UserProfileEntity userProfileEntity) {
		if(userProfileEntity == null) {
			return null;
		}

		//--- Generic mapping 
		UserProfile userProfile = map(userProfileEntity, UserProfile.class);

		return userProfile;
	}
	
	/**
	 * Mapping from 'UserProfile' to 'UserProfileEntity'
	 * @param userProfile
	 * @param userProfileEntity
	 */
	public void mapUserProfileToUserProfileEntity(UserProfile userProfile, UserProfileEntity userProfileEntity) {
		if(userProfile == null) {
			return;
		}

		//--- Generic mapping 
		map(userProfile, userProfileEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}