/*
 * Created on 4 May 2016 ( Time 15:52:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.cas.web.common.AbstractController;
import com.cas.web.common.FormMode;
import com.cas.web.common.Message;
import com.cas.web.common.MessageType;

//--- Entities
import com.cas.bean.AppUserUserProfile;

//--- Services 
import com.cas.business.service.AppUserUserProfileService;


/**
 * Spring MVC controller for 'AppUserUserProfile' management.
 */
@Controller
@RequestMapping("/appUserUserProfile")
public class AppUserUserProfileController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "appUserUserProfile";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "appUserUserProfile/form";
	private static final String JSP_LIST   = "appUserUserProfile/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/appUserUserProfile/create";
	private static final String SAVE_ACTION_UPDATE   = "/appUserUserProfile/update";

	//--- Main entity service
	@Resource
    private AppUserUserProfileService appUserUserProfileService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public AppUserUserProfileController() {
		super(AppUserUserProfileController.class, MAIN_ENTITY_NAME );
		log("AppUserUserProfileController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param appUserUserProfile
	 */
	private void populateModel(Model model, AppUserUserProfile appUserUserProfile, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, appUserUserProfile);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of AppUserUserProfile found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<AppUserUserProfile> list = appUserUserProfileService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new AppUserUserProfile
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		AppUserUserProfile appUserUserProfile = new AppUserUserProfile();	
		populateModel( model, appUserUserProfile, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing AppUserUserProfile
	 * @param model Spring MVC model
	 * @param userId  primary key element
	 * @param userProfileId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{userId}/{userProfileId}")
	public String formForUpdate(Model model, @PathVariable("userId") Long userId, @PathVariable("userProfileId") Long userProfileId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		AppUserUserProfile appUserUserProfile = appUserUserProfileService.findById(userId, userProfileId);
		populateModel( model, appUserUserProfile, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param appUserUserProfile  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid AppUserUserProfile appUserUserProfile, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				AppUserUserProfile appUserUserProfileCreated = appUserUserProfileService.create(appUserUserProfile); 
				model.addAttribute(MAIN_ENTITY_NAME, appUserUserProfileCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, appUserUserProfile.getUserId(), appUserUserProfile.getUserProfileId() );
			} else {
				populateModel( model, appUserUserProfile, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "appUserUserProfile.error.create", e);
			populateModel( model, appUserUserProfile, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param appUserUserProfile  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid AppUserUserProfile appUserUserProfile, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				AppUserUserProfile appUserUserProfileSaved = appUserUserProfileService.update(appUserUserProfile);
				model.addAttribute(MAIN_ENTITY_NAME, appUserUserProfileSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, appUserUserProfile.getUserId(), appUserUserProfile.getUserProfileId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, appUserUserProfile, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "appUserUserProfile.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, appUserUserProfile, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param userId  primary key element
	 * @param userProfileId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{userId}/{userProfileId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("userId") Long userId, @PathVariable("userProfileId") Long userProfileId) {
		log("Action 'delete'" );
		try {
			appUserUserProfileService.delete( userId, userProfileId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "appUserUserProfile.error.delete", e);
		}
		return redirectToList();
	}

}
