/*
 * Created on 4 May 2016 ( Time 15:51:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.cas.bean.AppUserUserProfile;
import com.cas.bean.jpa.AppUserUserProfileEntity;
import com.cas.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class AppUserUserProfileServiceMapperTest {

	private AppUserUserProfileServiceMapper appUserUserProfileServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		appUserUserProfileServiceMapper = new AppUserUserProfileServiceMapper();
		appUserUserProfileServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'AppUserUserProfileEntity' to 'AppUserUserProfile'
	 * @param appUserUserProfileEntity
	 */
	@Test
	public void testMapAppUserUserProfileEntityToAppUserUserProfile() {
		// Given
		AppUserUserProfileEntity appUserUserProfileEntity = new AppUserUserProfileEntity();
		
		// When
		AppUserUserProfile appUserUserProfile = appUserUserProfileServiceMapper.mapAppUserUserProfileEntityToAppUserUserProfile(appUserUserProfileEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'AppUserUserProfile' to 'AppUserUserProfileEntity'
	 */
	@Test
	public void testMapAppUserUserProfileToAppUserUserProfileEntity() {
		// Given
		AppUserUserProfile appUserUserProfile = new AppUserUserProfile();

		AppUserUserProfileEntity appUserUserProfileEntity = new AppUserUserProfileEntity();
		
		// When
		appUserUserProfileServiceMapper.mapAppUserUserProfileToAppUserUserProfileEntity(appUserUserProfile, appUserUserProfileEntity);
		
		// Then
	}

}