/*
 * Created on 4 May 2016 ( Time 15:52:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.cas.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
